// Sindicatos da construção civil por UF (lista de referência, principais entidades de trabalhadores).
// Fonte: federações estaduais da construção civil — atualize quando necessário.

export const UFS: { uf: string; name: string }[] = [
  { uf: "AC", name: "Acre" },
  { uf: "AL", name: "Alagoas" },
  { uf: "AP", name: "Amapá" },
  { uf: "AM", name: "Amazonas" },
  { uf: "BA", name: "Bahia" },
  { uf: "CE", name: "Ceará" },
  { uf: "DF", name: "Distrito Federal" },
  { uf: "ES", name: "Espírito Santo" },
  { uf: "GO", name: "Goiás" },
  { uf: "MA", name: "Maranhão" },
  { uf: "MT", name: "Mato Grosso" },
  { uf: "MS", name: "Mato Grosso do Sul" },
  { uf: "MG", name: "Minas Gerais" },
  { uf: "PA", name: "Pará" },
  { uf: "PB", name: "Paraíba" },
  { uf: "PR", name: "Paraná" },
  { uf: "PE", name: "Pernambuco" },
  { uf: "PI", name: "Piauí" },
  { uf: "RJ", name: "Rio de Janeiro" },
  { uf: "RN", name: "Rio Grande do Norte" },
  { uf: "RS", name: "Rio Grande do Sul" },
  { uf: "RO", name: "Rondônia" },
  { uf: "RR", name: "Roraima" },
  { uf: "SC", name: "Santa Catarina" },
  { uf: "SP", name: "São Paulo" },
  { uf: "SE", name: "Sergipe" },
  { uf: "TO", name: "Tocantins" },
];

export const SINDICATOS_POR_UF: Record<string, string[]> = {
  AC: ["CONFORME CATEGORIA DO ESTADO DO ACRE"],
  AL: ["CONFORME CATEGORIA DO ESTADO DE ALAGOAS"],
  AP: ["CONFORME CATEGORIA DO ESTADO DO AMAPÁ"],
  AM: ["CONFORME CATEGORIA DO ESTADO DO AMAZONAS"],
  BA: ["CONFORME CATEGORIA DO ESTADO DA BAHIA"],
  CE: ["CONFORME CATEGORIA DO ESTADO DO CEARÁ"],
  DF: ["CONFORME CATEGORIA DO ESTADO DO DISTRITO FEDERAL"],
  ES: ["CONFORME CATEGORIA DO ESTADO DO ESPIRITO SANTO"],
  GO: ["CONFORME CATEGORIA DO ESTADO DO GOIÁS"],
  MA: ["CONFORME CATEGORIA DO ESTADO DO MARANHÃO"],
  MT: ["CONFORME CATEGORIA DO ESTADO DO MATO GROSSO"],
  MS: ["CONFORME CATEGORIA DO ESTADO DO MATO GRASSO DO SUL"],
  MG: ["CONFORME CATEGORIA DO ESTADO DE MINAS GERAIS",],
  PA: ["CONFORME CATEGORIA DO ESTADO DO PARÁ"],
  PB: ["CONFORME CATEGORIA DO ESTADO DA PARAÍBA"],
  PR: ["CONFORME CATEGORIA DO ESTADO DO PARANÁ"],
  PE: ["CONFORME CATEGORIA DO ESTADO DE PERNANBUCO"],
  PI: ["CONFORME CATEGORIA DO ESTADO DO PIAUÍ"],
  RJ: ["CONFORME CATEGORIA DO ESTADO DO RIO DE JANEIRO"],
  RN: ["CONFORME CATEGORIA DO ESTADO DO RIO GRANDE DO NORTE"],
  RS: ["CONFORME CATEGORIA DO ESTADO DO RIO GRANDE DO SUL"],
  RO: ["CONFORME CATEGORIA DO ESTADO DE RONDÔNIA"],
  RR: ["CONFORME CATEGORIA DO ESTADO DE RORAIMA"],
  SC: ["CONFORME CATEGORIA DO ESTADO DE SANTA CATARINA"],
  SP: ["CONFORME CATEGORIA DO ESTADO DE SÃO PAULO"],
  SE: ["CONFORME CATEGORIA DO ESTADO DE SERGIPE"],
  TO: ["CONFORME CATEGORIA DO ESTADO DO TOCANTINS"],
};
