// Sindicatos da construção civil por UF (lista de referência, principais entidades de trabalhadores).
// Fonte: federações estaduais da construção civil — atualize quando necessário.

export const UFS: { uf: string; name: string }[] = [
  { uf: "AC", name: "Acre" },
  { uf: "AL", name: "Alagoas" },
  { uf: "AP", name: "Amapá" },
  { uf: "AM", name: "Amazonas" },
  { uf: "BA", name: "Bahia" },
  { uf: "CE", name: "Ceará" },
  { uf: "DF", name: "Distrito Federal" },
  { uf: "ES", name: "Espírito Santo" },
  { uf: "GO", name: "Goiás" },
  { uf: "MA", name: "Maranhão" },
  { uf: "MT", name: "Mato Grosso" },
  { uf: "MS", name: "Mato Grosso do Sul" },
  { uf: "MG", name: "Minas Gerais" },
  { uf: "PA", name: "Pará" },
  { uf: "PB", name: "Paraíba" },
  { uf: "PR", name: "Paraná" },
  { uf: "PE", name: "Pernambuco" },
  { uf: "PI", name: "Piauí" },
  { uf: "RJ", name: "Rio de Janeiro" },
  { uf: "RN", name: "Rio Grande do Norte" },
  { uf: "RS", name: "Rio Grande do Sul" },
  { uf: "RO", name: "Rondônia" },
  { uf: "RR", name: "Roraima" },
  { uf: "SC", name: "Santa Catarina" },
  { uf: "SP", name: "São Paulo" },
  { uf: "SE", name: "Sergipe" },
  { uf: "TO", name: "Tocantins" },
];

export const SINDICATOS_POR_UF: Record<string, string[]> = {
  AC: ["SINTRACOM/AC - Sind. Trab. Ind. Construção Civil do Acre"],
  AL: ["SINTRICCAL - Sind. Trab. Ind. Constr. Civil de Alagoas"],
  AP: ["SINTICCMAP - Sind. Trab. Ind. Constr. Civil e Mobiliário do Amapá"],
  AM: ["SINTRACOMEC/AM - Sind. Trab. Construção Civil do Amazonas"],
  BA: [
    "STICCB - Sind. Trab. Ind. Constr. Civil de Salvador",
    "SINTRACOM-BA - Sind. Trab. Constr. Civil da Bahia",
  ],
  CE: ["SINTEPAV-CE", "SINDUSCON-CE (patronal)", "STICC-CE - Sind. Trab. Ind. Constr. Civil do Ceará"],
  DF: ["SINTRACON-DF - Sind. Trab. Ind. Constr. Civil do Distrito Federal"],
  ES: ["SINTRACONST/ES - Sind. Trab. Ind. Constr. Civil do Espírito Santo"],
  GO: ["SINTRACON-GO - Sind. Trab. Ind. Constr. Civil de Goiás"],
  MA: ["SINTRACON-MA - Sind. Trab. Ind. Constr. Civil do Maranhão"],
  MT: ["SINTICOM-MT - Sind. Trab. Ind. Constr. Mobiliário Mato Grosso"],
  MS: ["SITRICOM-MS - Sind. Trab. Ind. Constr. Civil de MS"],
  MG: [
    "SINTRACONMG - Sind. Trab. Ind. Constr. Civil de Belo Horizonte",
    "SINTRACOMG - Sind. Trab. Ind. Constr. Civil de Contagem e Região",
  ],
  PA: ["SINTEPP/CC-PA - Sind. Trab. Constr. Civil do Pará"],
  PB: ["SINTRICOM/PB - Sind. Trab. Ind. Constr. Civil da Paraíba"],
  PR: [
    "SINTRACON-CURITIBA - Sind. Trab. Ind. Constr. Civil de Curitiba",
    "SINTRACONPAR - Sind. Trab. Ind. Constr. Civil do Paraná",
  ],
  PE: ["SINTEPAV-PE", "SINTICOM-PE - Sind. Trab. Ind. Constr. Civil de Pernambuco"],
  PI: ["SINTRICCMOPI - Sind. Trab. Ind. Constr. Civil do Piauí"],
  RJ: [
    "STICC-RJ - Sind. Trab. Ind. Constr. Civil do Rio de Janeiro",
    "SINTRACOMRJ - Sind. Trab. Ind. Constr. Civil do Estado do RJ",
  ],
  RN: ["SINTRACOM-RN - Sind. Trab. Ind. Constr. Civil do RN"],
  RS: [
    "STICC POA - Sind. Trab. Ind. Constr. Civil de Porto Alegre",
    "SINTRAICC-RS - Sind. Trab. Ind. Constr. Civil do Rio Grande do Sul",
  ],
  RO: ["SINTRACOM-RO - Sind. Trab. Ind. Constr. Civil de Rondônia"],
  RR: ["SINTRACOM-RR - Sind. Trab. Ind. Constr. Civil de Roraima"],
  SC: [
    "SINTRACOM-FLORIPA - Sind. Trab. Ind. Constr. Civil da Grande Florianópolis",
    "SINTRACONST-SC - Sind. Trab. Ind. Constr. Civil de Santa Catarina",
  ],
  SP: [
    "SINTRACON-SP - Sind. Trab. Ind. Constr. Civil de São Paulo",
    "SINTRACON-CAMPINAS - Sind. Trab. Ind. Constr. Civil de Campinas",
    "SINTRACOMOS - Sind. Trab. Ind. Constr. Civil de Osasco e Região",
    "SINTRACOM ABC - Sind. Trab. Ind. Constr. Civil do ABC",
  ],
  SE: ["SINTRICOM-SE - Sind. Trab. Ind. Constr. Civil de Sergipe"],
  TO: ["SINTRACONST-TO - Sind. Trab. Ind. Constr. Civil do Tocantins"],
};
