/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RdvRouteImport } from './routes/rdv'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HorasExtrasRouteImport } from './routes/horas-extras'
import { Route as FolhaSalarialRouteImport } from './routes/folha-salarial'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FuncionariosIndexRouteImport } from './routes/funcionarios.index'
import { Route as RdvIdRouteImport } from './routes/rdv_.$id'
import { Route as ObrasIdRouteImport } from './routes/obras_.$id'
import { Route as FuncionariosNovoRouteImport } from './routes/funcionarios.novo'
import { Route as FuncionariosFeriasRouteImport } from './routes/funcionarios.ferias'
import { Route as FuncionariosIdRouteImport } from './routes/funcionarios.$id'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminDemissoesRouteImport } from './routes/admin/demissoes'

const RdvRoute = RdvRouteImport.update({
  id: '/rdv',
  path: '/rdv',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HorasExtrasRoute = HorasExtrasRouteImport.update({
  id: '/horas-extras',
  path: '/horas-extras',
  getParentRoute: () => rootRouteImport,
} as any)
const FolhaSalarialRoute = FolhaSalarialRouteImport.update({
  id: '/folha-salarial',
  path: '/folha-salarial',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosIndexRoute = FuncionariosIndexRouteImport.update({
  id: '/funcionarios/',
  path: '/funcionarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const RdvIdRoute = RdvIdRouteImport.update({
  id: '/rdv_/$id',
  path: '/rdv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdRoute = ObrasIdRouteImport.update({
  id: '/obras_/$id',
  path: '/obras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosNovoRoute = FuncionariosNovoRouteImport.update({
  id: '/funcionarios/novo',
  path: '/funcionarios/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosFeriasRoute = FuncionariosFeriasRouteImport.update({
  id: '/funcionarios/ferias',
  path: '/funcionarios/ferias',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosIdRoute = FuncionariosIdRouteImport.update({
  id: '/funcionarios/$id',
  path: '/funcionarios/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemissoesRoute = AdminDemissoesRouteImport.update({
  id: '/admin/demissoes',
  path: '/admin/demissoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos': typeof DocumentosRoute
  '/folha-salarial': typeof FolhaSalarialRoute
  '/horas-extras': typeof HorasExtrasRoute
  '/login': typeof LoginRoute
  '/obras': typeof ObrasRoute
  '/rdv': typeof RdvRoute
  '/admin/demissoes': typeof AdminDemissoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/funcionarios/$id': typeof FuncionariosIdRoute
  '/funcionarios/ferias': typeof FuncionariosFeriasRoute
  '/funcionarios/novo': typeof FuncionariosNovoRoute
  '/obras/$id': typeof ObrasIdRoute
  '/rdv/$id': typeof RdvIdRoute
  '/funcionarios/': typeof FuncionariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos': typeof DocumentosRoute
  '/folha-salarial': typeof FolhaSalarialRoute
  '/horas-extras': typeof HorasExtrasRoute
  '/login': typeof LoginRoute
  '/obras': typeof ObrasRoute
  '/rdv': typeof RdvRoute
  '/admin/demissoes': typeof AdminDemissoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/funcionarios/$id': typeof FuncionariosIdRoute
  '/funcionarios/ferias': typeof FuncionariosFeriasRoute
  '/funcionarios/novo': typeof FuncionariosNovoRoute
  '/obras/$id': typeof ObrasIdRoute
  '/rdv/$id': typeof RdvIdRoute
  '/funcionarios': typeof FuncionariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentos': typeof DocumentosRoute
  '/folha-salarial': typeof FolhaSalarialRoute
  '/horas-extras': typeof HorasExtrasRoute
  '/login': typeof LoginRoute
  '/obras': typeof ObrasRoute
  '/rdv': typeof RdvRoute
  '/admin/demissoes': typeof AdminDemissoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/funcionarios/$id': typeof FuncionariosIdRoute
  '/funcionarios/ferias': typeof FuncionariosFeriasRoute
  '/funcionarios/novo': typeof FuncionariosNovoRoute
  '/obras_/$id': typeof ObrasIdRoute
  '/rdv_/$id': typeof RdvIdRoute
  '/funcionarios/': typeof FuncionariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/documentos'
    | '/folha-salarial'
    | '/horas-extras'
    | '/login'
    | '/obras'
    | '/rdv'
    | '/admin/demissoes'
    | '/admin/usuarios'
    | '/funcionarios/$id'
    | '/funcionarios/ferias'
    | '/funcionarios/novo'
    | '/obras/$id'
    | '/rdv/$id'
    | '/funcionarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/documentos'
    | '/folha-salarial'
    | '/horas-extras'
    | '/login'
    | '/obras'
    | '/rdv'
    | '/admin/demissoes'
    | '/admin/usuarios'
    | '/funcionarios/$id'
    | '/funcionarios/ferias'
    | '/funcionarios/novo'
    | '/obras/$id'
    | '/rdv/$id'
    | '/funcionarios'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/documentos'
    | '/folha-salarial'
    | '/horas-extras'
    | '/login'
    | '/obras'
    | '/rdv'
    | '/admin/demissoes'
    | '/admin/usuarios'
    | '/funcionarios/$id'
    | '/funcionarios/ferias'
    | '/funcionarios/novo'
    | '/obras_/$id'
    | '/rdv_/$id'
    | '/funcionarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DocumentosRoute: typeof DocumentosRoute
  FolhaSalarialRoute: typeof FolhaSalarialRoute
  HorasExtrasRoute: typeof HorasExtrasRoute
  LoginRoute: typeof LoginRoute
  ObrasRoute: typeof ObrasRoute
  RdvRoute: typeof RdvRoute
  AdminDemissoesRoute: typeof AdminDemissoesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  FuncionariosIdRoute: typeof FuncionariosIdRoute
  FuncionariosFeriasRoute: typeof FuncionariosFeriasRoute
  FuncionariosNovoRoute: typeof FuncionariosNovoRoute
  ObrasIdRoute: typeof ObrasIdRoute
  RdvIdRoute: typeof RdvIdRoute
  FuncionariosIndexRoute: typeof FuncionariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rdv': {
      id: '/rdv'
      path: '/rdv'
      fullPath: '/rdv'
      preLoaderRoute: typeof RdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horas-extras': {
      id: '/horas-extras'
      path: '/horas-extras'
      fullPath: '/horas-extras'
      preLoaderRoute: typeof HorasExtrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folha-salarial': {
      id: '/folha-salarial'
      path: '/folha-salarial'
      fullPath: '/folha-salarial'
      preLoaderRoute: typeof FolhaSalarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios/': {
      id: '/funcionarios/'
      path: '/funcionarios'
      fullPath: '/funcionarios/'
      preLoaderRoute: typeof FuncionariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rdv_/$id': {
      id: '/rdv_/$id'
      path: '/rdv/$id'
      fullPath: '/rdv/$id'
      preLoaderRoute: typeof RdvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras_/$id': {
      id: '/obras_/$id'
      path: '/obras/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof ObrasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios/novo': {
      id: '/funcionarios/novo'
      path: '/funcionarios/novo'
      fullPath: '/funcionarios/novo'
      preLoaderRoute: typeof FuncionariosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios/ferias': {
      id: '/funcionarios/ferias'
      path: '/funcionarios/ferias'
      fullPath: '/funcionarios/ferias'
      preLoaderRoute: typeof FuncionariosFeriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios/$id': {
      id: '/funcionarios/$id'
      path: '/funcionarios/$id'
      fullPath: '/funcionarios/$id'
      preLoaderRoute: typeof FuncionariosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demissoes': {
      id: '/admin/demissoes'
      path: '/admin/demissoes'
      fullPath: '/admin/demissoes'
      preLoaderRoute: typeof AdminDemissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DocumentosRoute: DocumentosRoute,
  FolhaSalarialRoute: FolhaSalarialRoute,
  HorasExtrasRoute: HorasExtrasRoute,
  LoginRoute: LoginRoute,
  ObrasRoute: ObrasRoute,
  RdvRoute: RdvRoute,
  AdminDemissoesRoute: AdminDemissoesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  FuncionariosIdRoute: FuncionariosIdRoute,
  FuncionariosFeriasRoute: FuncionariosFeriasRoute,
  FuncionariosNovoRoute: FuncionariosNovoRoute,
  ObrasIdRoute: ObrasIdRoute,
  RdvIdRoute: RdvIdRoute,
  FuncionariosIndexRoute: FuncionariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
